[package]
name = "hwid"
version = "0.1.0"
authors = ["S Stewart <iamtheworst@programmer.net>"]
edition = "2018"

# https://stackoverflow.com/a/51821632/364875
[target.'cfg(target_os = "windows")'.dependencies]
winreg = "0.6"
